###############-VERSION-###################
version: '3.3'

################-SERVICIOS-################

services:

###################-SERVIDOR-#########################   
   servidor:
    container_name: servidor
    build: ./backend
    restart: always
    env_file: .env
    ports:
        - "50051:50051"
    #volumes:
    #    - ./backend:/backend
    environment:
        FLASK_ENV: development

    depends_on:
        - postgres

###################-CLIENTE-#########################   
   cliente:
    container_name: cliente
    build: ./client
    restart: always
    ports:
        - "8000:5000"
    environment:
        FLASK_ENV: development

    depends_on:
        - postgres
        - redis1
        - redis2
        - redis3
        - servidor

###################-REDIS_SHARPS-##########################
   redis1:
    container_name: redis1
    image: redis:6.2.6
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis1",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-lfu"
      ]

   redis2:
    container_name: redis2
    image: redis:6.2.6
    restart: always
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis2",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-lfu"
      ]
  
   redis3:
    container_name: redis3
    image: redis:6.2.6
    restart: always
    ports:
      - "6381:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis3",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-random"
      ]
    

#################-POSTGRES-##########################
   postgres:
    container_name: postgres
    image: bitnami/postgresql:12.10.0
    restart: always
    volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
        - .env
    ports:
        - "5432:5432"
    environment:
        - POSTGRESQL_USER=${POSTGRES_USER}
        - POSTGRESQL_DATABASE=${POSTGRES_DB}
        - ALLOW_EMPTY_PASSWORD=${HIDE_EMPTY_PASSWORD}
        - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}

    

