version: "3.9"

networks:
  my_network:

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    networks:
      - my_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      - my_network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

    depends_on:
      - zookeeper

  producer:
    container_name: producer
    networks:
      - my_network
    build: ./Producer
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - zookeeper
  
  consumer:
    container_name: consumer
    networks:
      - my_network
    build: ./Consumer
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - zookeeper
      - producer