###############-VERSION-###################
version: '3.3'

################-SERVICIOS-################

services:

###################-SERVIDOR-#########################   
   servidor:
    container_name: servidor
    build: ./backend
    restart: always
    env_file: .env
    ports:
        - "3000:50051"
    #volumes:
    #    - ./backend:/backend
    environment:
        FLASK_ENV: development

    depends_on:
        - postgres
        - redis

###################-CLIENTE-#########################   
   cliente:
    container_name: cliente
    build: ./client
    restart: always
    env_file: .env
    ports:
        - "3002:5000"
    environment:
        FLASK_ENV: development

    depends_on:
        - postgres
        - redis
        - servidor

###################-REDIS_SV-##########################
   redis:
    container_name: cache
    image: redis:6.2.6
    restart: always
    ports:
        - "3001:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - ALLOW_EMPTY_PASSWORD=yes
    command: ["redis-server", "--bind", "redis","--maxmemory 2mb","--maxmemory-policy allkeys-lru"]

#################-POSTGRES-##########################
   postgres:
    container_name: postgres
    image: bitnami/postgresql:14.2.0-debian-10-r64
    restart: always
    volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
        - .env
    ports:
        - "5432:5432"
    environment:
        - POSTGRESQL_USER=${POSTGRES_USER}
        - POSTGRESQL_DATABASE=${POSTGRES_DB}
        - ALLOW_EMPTY_PASSWORD=${HIDE_EMPTY_PASSWORD}
        - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}

    

