###############-VERSION-###################
version: '3.3'

################-SERVICIOS-################

services:

###################-SERVIDOR-#########################   
   servidor:
    container_name: servidor
    build: ./backend
    restart: always
    ports:
        - "3000:5000"
    volumes:
        - ./backend:/backend
    environment:
        FLASK_ENV: development

###################-REDIS_SV-##########################
   redis:
    container_name: cache
    image: redis:6.2.6
    restart: always
    ports:
        - "3001:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
      - ALLOW_EMPTY_PASSWORD=yes
    command: ["redis-server", "--bind", "redis","--maxmemory 2mb","--maxmemory-policy allkeys-lru"]

#################-POSTGRES-##########################
   postgres:
    container_name: postgres
    image: docker.io/bitnami/postgresql:11
    restart: always
    volumes:
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
        - db.env
    ports:
        - "5432:5432"
    environment:
        - POSTGRESQL_USER=${POSTGRES_USER}
        - POSTGRESQL_DATABASE=${POSTGRES_DB}
        - ALLOW_EMPTY_PASSWORD=${HIDE_EMPTY_PASSWORD}
        - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}

    

